function [E_yij, E_inv_yij] = E_step(Y, init_a, TNi, model, eta, n)

E_yij_obs = cell(n,1);
E_inv_yij_obs = cell(n,1);
E_yij_miss_1 = cell(n,1);
E_inv_yij_miss_1 = cell(n,1);
E_yij_miss_2 = cell(n,1);
E_inv_yij_miss_2 = cell(n,1);
E_yij = cell(n,1);
E_inv_yij = cell(n,1);
t_int = 0.4;
epsilon = 1e-6;

for i = 1:length(Y)
    t = TNi{i};
    y = Y{i};

    % 根据模型计算 lambda(t)
    switch model
        case 'linear'
            lambda = @(t) init_a * t; % lambda 是 t 的函数
        case 'quadratic'
            lambda = @(t) init_a * (t.^2 / 10); % lambda 是二次函数
        case 'sqrt'
            lambda = @(t) init_a * sqrt(10 * t); % lambda 是平方根函数
        otherwise
            warning('Unknown model type');
    end

    for j =1:length(y)

        E_yij_miss_1{i} = cell(length(y), 1);
        E_yij_miss_2{i} = cell(length(y), 1);
        E_inv_yij_miss_1{i} = cell(length(y), 1);
        E_inv_yij_miss_2{i} = cell(length(y), 1);

        if j == 1

            if abs(t(j) - t_int*2) < epsilon

                delta_t = y(j) - 0;
                
                E_yij_miss_1{i}{j}(2) = delta_t * (lambda(t(j)) - lambda(t_int*(2-1))) / (lambda(t(j)) - lambda(0));
                E_yij_miss_1{i}{j}(1) = delta_t * (lambda(t_int*(2-1)) - lambda(0)) / (lambda(t(j)) - lambda(0));

                E_inv_yij_miss_1{i}{j}(1) = (lambda(t(j)) - lambda(t_int*(2-1))) / ...
                    (eta*(lambda(t_int*(2-1)) - lambda(0))^2 * (lambda(t(j))-lambda(t_int*(2-1))))+...
                    (lambda(t(j)) - lambda(0)) / (lambda(t_int*(2-1)) - lambda(0)) * delta_t^(-1);
                E_inv_yij_miss_1{i}{j}(2) = ( lambda(t_int*(2-1)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(2-1)))^2 * (lambda(t(j)) - lambda(0)))+...
                    (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(2-1))) * delta_t^(-1);

                E_yij_obs{i} = [E_yij_miss_1{i}{j}(1), E_yij_miss_1{i}{j}(2)];
                E_inv_yij_obs{i} = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2)];
                negative_num = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2)];
                if any(negative_num < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end



            elseif abs(t(j) - t_int*3) < epsilon

                delta_t = y(j) - 0;

                E_yij_miss_1{i}{j}(3) = delta_t * (lambda(t(j)) - lambda(t_int*(3-1))) / (lambda(t(j)) - lambda(t_int*(3-2)))...
                    * (lambda(t(j)) - lambda(t_int*(3-2))) / (lambda(t(j)) - lambda(0));
                E_yij_miss_1{i}{j}(2) = delta_t * (lambda(t_int*(3-1)) - lambda(t_int*(3-2))) / (lambda(t(j)) - lambda(0))...
                    *(lambda(t(j)) - lambda(t_int*(3-2))) / (lambda(t(j)) - lambda(0)) * delta_t;
                E_yij_miss_1{i}{j}(1) = delta_t * (lambda(t_int*(3-2)) - lambda(0)) / (lambda(t_int*(3-1)) - lambda(0))...
                    * (lambda(t_int*(3-2)) - lambda(0)) / (lambda(t(j)) - lambda(0));

                E_inv_yij_miss_1{i}{j}(3) = (lambda(t_int*(3-1)) - lambda(t_int*(3-2))) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(3-1)))^2 * (lambda(t(j)) - lambda(t_int*(3-2))))...
                    + (lambda(t(j)) - lambda(t_int*(3-2))) / (lambda(t(j)) - lambda(t_int*(3-1)))...
                    * ((lambda(t_int*(3-2)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(3-2)))^2 * (lambda(t(j)) - lambda(0))) ...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(3-2))) * delta_t^(-1));
                E_inv_yij_miss_1{i}{j}(2) = (lambda(t(j)) - lambda(t_int*(3-1))) / ...
                    (eta*(lambda(t_int*(3-1)) - lambda(t_int*(3-2)))^2 * (lambda(t(j)) - lambda(t_int*(3-2))))...
                    + (lambda(t(j)) - lambda(t_int*(3-2))) / (lambda(t_int*(3-1)) - lambda(t_int*(3-2)))...
                    * ((lambda(t_int*(3-2)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(3-2)))^2 * (lambda(t(j)) - lambda(0))) ...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(3-2))) * delta_t^(-1));
                E_inv_yij_miss_1{i}{j}(1) = (lambda(t_int*(3-1)) - lambda(t_int*(3-2))) / ...
                    (eta*(lambda(t_int*(3-2)) - lambda(0))^2 * (lambda(t_int*(3-1)) - lambda(0)))+...
                    (lambda(t_int*(3-1)) - lambda(0)) / (lambda(t_int*(3-2)) - lambda(0))...
                    * ((lambda(t(j)) - lambda(t_int*(3-1))) / ...
                    (eta*(lambda(t_int*(3-1)) - lambda(0))^2 * (lambda(t(j)) - lambda(0))) ...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t_int*(3-1)) - lambda(0)) * delta_t^(-1));

                E_yij_obs{i} = [E_yij_miss_1{i}{j}(1), E_yij_miss_1{i}{j}(2), E_yij_miss_1{i}{j}(3)];
                E_inv_yij_obs{i} = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3)];
                negative_num = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3)];
                if any(negative_num < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end


            elseif abs(t(j) - t_int*4) < epsilon

                delta_t = y(j) - 0;

                E_yij_miss_1{i}{j}(4) = delta_t * (lambda(t(j)) - lambda(t_int*(4-1))) / (lambda(t(j)) - lambda(t_int*(4-2)))...
                    * (lambda(t(j)) - lambda(t_int*(4-2))) / (lambda(t(j)) - lambda(t_int*(4-1)))...
                    * (lambda(t(j)) - lambda(t_int*(4-3))) / (lambda(t(j)) - lambda(0));
                E_yij_miss_1{i}{j}(3) = delta_t * (lambda(t_int*(4-1)) - lambda(t_int*(4-2))) / (lambda(t(j)) - lambda(t_int*(4-2)))...
                    * (lambda(t(j)) - lambda(t_int*(4-2))) / (lambda(t(j)) - lambda(t_int*(4-3)))...
                    * (lambda(t(j)) - lambda(t_int*(4-3))) / (lambda(t(j)) - lambda(0));
                E_yij_miss_1{i}{j}(2) = delta_t * (lambda(t_int*(4-2)) - lambda(t_int*(4-3))) / (lambda(t_int*(4-1)) - lambda(t_int*(4-3)))...
                    * (lambda(t_int*(4-1)) - lambda(t_int*(4-3))) / (lambda(t(j)) - lambda(t_int*(4-3))) ...
                    * (lambda(t(j)) - lambda(t_int*(4-3))) / (lambda(t(j)) - lambda(0));
                E_yij_miss_1{i}{j}(1) = delta_t * (lambda(t_int*(4-3)) - lambda(0)) / (lambda(t_int*(4-2)) - lambda(0))...
                    * (lambda(t_int*(4-2)) - lambda(0)) / (lambda(t_int*(4-1)) - lambda(0))...
                    * (lambda(t_int*(4-1)) - lambda(0)) / (lambda(t(j)) - lambda(0));

                E_inv_yij_miss_1{i}{j}(4) = (lambda(t_int*(4-1)) - lambda(t_int*(4-2))) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(4-1)))^2 * (lambda(t(j)) - lambda(t_int*(4-2))))...
                    + (lambda(t(j)) - lambda(t_int*(4-2))) / (lambda(t(j)) - lambda(t_int*(4-1)))...
                    * ((lambda(t_int*(4-2)) - lambda(t_int*(4-3))) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(4-2)))^2 * (lambda(t(j)) - lambda(t_int*(4-3))))...
                    + (lambda(t(j)) - lambda(t_int*(4-3))) / (lambda(t(j)) - lambda(t_int*(4-2)))...
                    * ((lambda(t_int*(4-3)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(4-3)))^2 * (lambda(t(j)) - lambda(0)))...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(4-3))) * delta_t^(-1)));
                E_inv_yij_miss_1{i}{j}(3) = (lambda(t(j)) - lambda(t_int*(4-1))) / ...
                    (eta*(lambda(t_int*(4-1)) - lambda(t_int*(4-2)))^2 * (lambda(t(j)) - lambda(t_int*(4-2))))...
                    + (lambda(t(j)) - lambda(t_int*(4-2))) / (lambda(t_int*(4-1)) - lambda(t_int*(4-2)))...
                    * ((lambda(t_int*(4-2)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(4-2)))^2 * (lambda(t(j)) - lambda(t_int*(4-3))))...
                    + (lambda(t(j)) - lambda(t_int*(4-3))) / (lambda(t(j)) - lambda(t_int*(4-2)))...
                    * ((lambda(t_int*(4-3)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(4-3)))^2 * (lambda(t(j)) - lambda(0)))...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(4-3))) * delta_t^(-1)));
                E_inv_yij_miss_1{i}{j}(2) = (lambda(t_int*(4-1)) - lambda(t_int*(4-2))) / ...
                    (eta*(lambda(t_int*(4-2)) - lambda(t_int*(4-3)))^2 * (lambda(t_int*(4-1)) - lambda(t_int*(4-3))))...
                    + (lambda(t_int*(4-1)) - lambda(t_int*(4-3))) / (lambda(t_int*(4-2)) - lambda(t_int*(4-3)))...
                    * ((lambda(t(j)) - lambda(t_int*(4-1))) / ...
                    (eta*(lambda(t_int*(4-1)) - lambda(t_int*(4-3)))^2 * (lambda(t(j)) - lambda(t_int*(4-1)))) ...
                    + (lambda(t(j)) - lambda(t_int*(4-1))) / (lambda(t_int*(4-1)) - lambda(t_int*(4-3))) ...
                    * ((lambda(t_int*(4-3)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(4-3)))^2 * (lambda(t(j)) - lambda(0))) ...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(4-3))) * delta_t^(-1)));
                E_inv_yij_miss_1{i}{j}(4) = (lambda(t_int*(4-2)) - lambda(t_int*(4-3))) / ...
                    (eta*(lambda(t_int*(4-3)) - lambda(0))^2 * (lambda(t_int*(4-2)) - lambda(0)))...
                    + (lambda(t_int*(4-2)) - lambda(0)) / (lambda(t_int*(4-2)) - lambda(t_int*(4-3)))...
                    * ((lambda(t_int*(4-1)) - lambda(t_int*(4-2))) / ...
                    (eta*(lambda(t_int*(4-2)) - lambda(0))^2 * (lambda(t_int*(4-1)) - lambda(0)))...
                    + (lambda(t_int*(4-1)) - lambda(0)) / (lambda(t_int*(4-1)) - lambda(t_int*(4-2)))...
                    * ((lambda(t(j)) - lambda(t_int*(4-1))) / ...
                    (eta*(lambda(t_int*(4-1)) - lambda(0))^2 * (lambda(t(j)) - lambda(0)))...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(4-1))) * delta_t^(-1)));

                E_yij_obs{i} = [E_yij_miss_1{i}{j}(1), E_yij_miss_1{i}{j}(2), E_yij_miss_1{i}{j}(3), E_yij_miss_1{i}{j}(4)];
                E_inv_yij_obs{i} = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3), E_inv_yij_miss_1{i}{j}(4)];
                negative_num = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3), E_inv_yij_miss_1{i}{j}(4)];
                if any(negative_num < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end


            elseif abs(t(j) - t_int*5) < epsilon

                delta_t = y(j) - 0;

                E_yij_miss_1{i}{j}(5) = delta_t * (lambda(t(j)) - lambda(t_int*(5-1))) / (lambda(t(j)) - lambda(t_int*(5-2)))...
                    * (lambda(t(j)) - lambda(t_int*(5-2))) / (lambda(t(j)) - lambda(t_int*(5-3)))...
                    * (lambda(t(j)) - lambda(t_int*(5-3))) / (lambda(t(j)) - lambda(t_int*(5-4)))...
                    * (lambda(t(j)) - lambda(t_int*(5-4))) / (lambda(t(j)) - lambda(0));
                E_yij_miss_1{i}{j}(4) = delta_t * (lambda(t_int*(5-1)) - lambda(t_int*(5-2))) / (lambda(t(j)) - lambda(t_int*(5-2)))...
                    * (lambda(t(j)) - lambda(t_int*(5-2))) / (lambda(t(j)) - lambda(t_int*(5-3)))...
                    * (lambda(t(j)) - lambda(t_int*(5-3))) / (lambda(t(j)) - lambda(t_int*(5-4)))...
                    * (lambda(t(j)) - lambda(t_int*(5-4))) / (lambda(t(j)) - lambda(0));
                E_yij_miss_1{i}{j}(3) = delta_t * (lambda(t_int*(5-2)) - lambda(t_int*(5-3))) / (lambda(t_int*(5-1)) - lambda(t_int*(5-3)))...
                    * (lambda(t_int*(5-1)) - lambda(t_int*(5-3))) / (lambda(t(j)) - lambda(t_int*(5-3)))...
                    * (lambda(t(j)) - lambda(t_int*(5-3))) / (lambda(t(j)) - lambda(t_int*(5-4)))...
                    * (lambda(t(j)) - lambda(t_int*(5-4))) / (lambda(t(j)) - lambda(0));
                E_yij_miss_1{i}{j}(2) = delta_t * (lambda(t_int*(5-3)) - lambda(t_int*(5-4))) / (lambda(t_int*(5-2)) - lambda(t_int*(5-4)))...
                    * (lambda(t_int*(5-2)) - lambda(t_int*(5-4))) / (lambda(t_int*(5-1)) - lambda(t_int*(5-4)))...
                    * (lambda(t_int*(5-1)) - lambda(t_int*(5-4))) / (lambda(t(j)) - lambda(t_int*(5-4)))...
                    * (lambda(t(j)) - lambda(t_int*(5-4))) / (lambda(t(j)) - lambda(0));
                E_yij_miss_1{i}{j}(1) = delta_t * (lambda(t_int*(5-4)) - lambda(0)) / (lambda(t_int*(5-3)) - lambda(0))...
                    * (lambda(t_int*(5-3)) - lambda(0)) / (lambda(t_int*(5-2)) - lambda(0))...
                    * (lambda(t_int*(5-2)) - lambda(0)) / (lambda(t_int*(5-1)) - lambda(0))...
                    * (lambda(t_int*(5-1)) - lambda(0)) / (lambda(t(j)) - lambda(0));

                E_inv_yij_miss_1{i}{j}(5) = (lambda(t_int*(5-1)) - lambda(t_int*(5-2))) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-1)))^2 * (lambda(t(j)) - lambda(t_int*(5-2))))...
                    + (lambda(t(j)) - lambda(t_int*(5-2))) / (lambda(t(j)) - lambda(t_int*(5-1)))...
                    * ((lambda(t_int*(5-2)) - lambda(t_int*(5-3))) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-2)))^2 * (lambda(t(j)) - lambda(t_int*(5-3))))...
                    + (lambda(t(j)) - lambda(t_int*(5-3))) / (lambda(t(j)) - lambda(t_int*(5-2)))...
                    * ((lambda(t_int*(5-3)) - lambda(t_int*(5-4))) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-3)))^2 * (lambda(t(j)) - lambda(t_int*(5-4))))...
                    + (lambda(t(j)) - lambda(t_int*(5-4))) / (lambda(t(j)) - lambda(t_int*(5-3)))...
                    * ((lambda(t_int*(5-4)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-4)))^2 * (lambda(t(j)) - lambda(0)))...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(5-4))) * delta_t^(-1))));
                E_inv_yij_miss_1{i}{j}(4) = (lambda(t(j)) - lambda(t_int*(5-1))) / ...
                    (eta*(lambda(t_int*(5-1)) - lambda(t_int*(5-2)))^2 * (lambda(t(j)) - lambda(t_int*(5-2))))...
                    + (lambda(t(j)) - lambda(t_int*(5-2))) / (lambda(t_int*(5-1)) - lambda(t_int*(5-2)))...
                    * ((lambda(t_int*(5-2)) - lambda(t_int*(5-3))) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-2)))^2 * (lambda(t(j)) - lambda(t_int*(5-3))))...
                    + (lambda(t(j)) - lambda(t_int*(5-3))) / (lambda(t(j)) - lambda(t_int*(5-2)))...
                    * ((lambda(t_int*(5-3)) - lambda(t_int*(5-4))) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-3)))^2 * (lambda(t(j)) - lambda(t_int*(5-4))))...
                    + (lambda(t(j)) - lambda(t_int*(5-4))) / (lambda(t(j)) - lambda(t_int*(5-3)))...
                    * ((lambda(t_int*(5-4)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-4)))^2 * (lambda(t(j)) - lambda(0)))...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(5-4))) * delta_t^(-1))));
                E_inv_yij_miss_1{i}{j}(3) = (lambda(t_int*(5-1)) - lambda(t_int*(5-2))) / ...
                    (eta*(lambda(t_int*(5-2)) - lambda(t_int*(5-3)))^2 * (lambda(t_int*(5-1)) - lambda(t_int*(5-3))))...
                    + (lambda(t_int*(5-1)) - lambda(t_int*(5-3))) / (lambda(t_int*(5-1)) - lambda(t_int*(5-2)))...
                    * ((lambda(t(j)) - lambda(t_int*(5-1))) / ...
                    (eta*(lambda(t_int*(5-1)) - lambda(t_int*(5-3)))^2 * (lambda(t(j)) - lambda(t_int*(5-3))))...
                    + (lambda(t(j)) - lambda(t_int*(5-3))) / (lambda(t(j)) - lambda(t_int*(5-1)))...
                    * ((lambda(t_int*(5-3)) - lambda(t_int*(5-4))) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-3)))^2 * (lambda(t(j)) - lambda(t_int*(5-4))))...
                    + (lambda(t(j)) - lambda(t_int*(5-4))) / (lambda(t(j)) - lambda(t_int*(5-3)))...
                    * ((lambda(t_int*(5-4)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-4)))^2 * (lambda(t(j)) - lambda(0)))...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(5-4))) * delta_t^(-1))));
                E_inv_yij_miss_1{i}{j}(2) = (lambda(t_int*(5-2)) - lambda(t_int*(5-3))) / ...
                    (eta*(lambda(t_int*(5-3)) - lambda(t_int*(5-4)))^2 * (lambda(t_int*(5-2)) - lambda(t_int*(5-1))))...
                    + (lambda(t_int*(5-2)) - lambda(t_int*(5-4))) / (lambda(t_int*(5-2)) - lambda(t_int*(5-3)))...
                    * ((lambda(t_int*(5-1)) - lambda(t_int*(5-2))) / ...
                    (eta*(lambda(t_int*(5-2)) - lambda(t_int*(5-4)))^2 * (lambda(t_int*(5-1)) - lambda(t_int*(5-4)))) ...
                    + (lambda(t_int*(5-1)) - lambda(t_int*(5-4))) / (lambda(t_int*(5-1)) - lambda(t_int*(5-2))) ...
                    * ((lambda(t(j)) - lambda(t_int*(5-1))) / ...
                    (eta*(lambda(t_int*(5-1)) - lambda(t_int*(5-4)))^2 * (lambda(t(j)) - lambda(t_int*(5-4)))) ...
                    + (lambda(t(j)) - lambda(t_int*(5-4))) / (lambda(t(j)) - lambda(t_int*(5-1)))...
                    * ((lambda(t_int*(5-4)) - lambda(0)) / ...
                    (eta*(lambda(t(j)) - lambda(t_int*(5-4)))^2 * (lambda(t(j)) - lambda(0)))...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(5-4))) * delta_t^(-1))));
                E_inv_yij_miss_1{i}{j}(1) = (lambda(t_int*(5-3)) - lambda(t_int*(5-4))) / ...
                    (eta*(lambda(t_int*(5-4)) - lambda(0))^2 * (lambda(t_int*(5-3)) - lambda(0)))...
                    + (lambda(t_int*(5-3)) - lambda(0)) / (lambda(t_int*(5-3)) - lambda(t_int*(5-4)))...
                    * ((lambda(t_int*(5-2)) - lambda(t_int*(5-3))) / ...
                    (eta*(lambda(t_int*(5-3)) - lambda(0))^2 * (lambda(t_int*(5-2)) - lambda(0)))...
                    + (lambda(t_int*(5-2)) - lambda(0)) / (lambda(t_int*(5-2)) - lambda(t_int*(5-3)))...
                    * ((lambda(t_int*(5-1)) - lambda(t_int*(5-2))) / ...
                    (eta*(lambda(t_int*(5-2)) - lambda(0))^2 * (lambda(t_int*(5-1)) - lambda(0)))...
                    + (lambda(t_int*(5-1)) - lambda(0)) / (lambda(t_int*(5-1)) - lambda(t_int*(5-2)))...
                    * ((lambda(t(j)) - lambda(t_int*(5-1))) / ...
                    (eta*(lambda(t_int*(5-1)) - lambda(0))^2 * (lambda(t(j)) - lambda(0)))...
                    + (lambda(t(j)) - lambda(0)) / (lambda(t(j)) - lambda(t_int*(5-1))) * delta_t^(-1))));

                E_yij_obs{i} = [E_yij_miss_1{i}{j}(1), E_yij_miss_1{i}{j}(2), E_yij_miss_1{i}{j}(3), E_yij_miss_1{i}{j}(4), E_yij_miss_1{i}{j}(5)];
                E_inv_yij_obs{i} = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3), E_inv_yij_miss_1{i}{j}(4), E_inv_yij_miss_1{i}{j}(5)];
                negative_num = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3), E_inv_yij_miss_1{i}{j}(4),E_inv_yij_miss_1{i}{j}(4)];
                if any(negative_num < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end

            else


                E_yij_obs{i} = [y(j)-0];
                E_inv_yij_obs{i} = [1 / E_yij_obs{i}(j)];
                negative_num = [1 / E_yij_obs{i}(j)];
                if any(negative_num < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end

            end


        elseif j >= 2 && j <= length(y)

            if abs(t(j) - t(j-1) - t_int*2) < epsilon
                delta_t = y(j) - y(j-1);

                E_yij_miss_1{i}{j}(2) = delta_t * (lambda(t(j)) - lambda(t(j-1) + t_int*(2-1))) / (lambda(t(j)) - lambda(t(j-1)));
                E_yij_miss_1{i}{j}(1) = delta_t * (lambda(t(j-1)+t_int*(2-1)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)));

                E_inv_yij_miss_1{i}{j}(1) = (lambda(t(j)) - lambda(t(j-1)+t_int*(2-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(2-1)) - lambda(t(j-1)))^2 * (lambda(t(j))-lambda(t(j-1)+t_int*(2-1))))+...
                    (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(2-1)) - lambda(t(j-1))) * delta_t^(-1);
                E_inv_yij_miss_1{i}{j}(2) = ( lambda(t(j-1)+t_int*(2-1)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(2-1)))^2 * (lambda(t(j)) - lambda(t(j-1))))+...
                    (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(2-1))) * delta_t^(-1);

                E_yij_obs{i} = [E_yij_obs{i}, E_yij_miss_1{i}{j}(1), E_yij_miss_1{i}{j}(2)];
                E_inv_yij_obs{i} = [E_inv_yij_obs{i}, E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2)];
                negative_num = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2)];
                if any(negative_num < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end

            elseif abs(t(j) - t(j-1) - t_int*3) < epsilon
                delta_t = y(j) - y(j-1);

                E_yij_miss_1{i}{j}(3) = delta_t * (lambda(t(j)) - lambda(t(j-1)+t_int*(3-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(3-2)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(3-2))) / (lambda(t(j)) - lambda(t(j-1)));
                E_yij_miss_1{i}{j}(2) = delta_t * (lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1)+t_int*(3-2))) / (lambda(t(j)) - lambda(t(j-1)))...
                    *(lambda(t(j)) - lambda(t(j-1)+t_int*(3-2))) / (lambda(t(j)) - lambda(t(j-1))) * delta_t;
                E_yij_miss_1{i}{j}(1) = delta_t * (lambda(t(j-1)+t_int*(3-2)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1)))...
                    * (lambda(t(j-1)+t_int*(3-2)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)));

                E_inv_yij_miss_1{i}{j}(3) = (lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1)+t_int*(3-2))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(3-1)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(3-2))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(3-2))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(3-1)))...
                    * ((lambda(t(j-1)+t_int*(3-2)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(3-2)))^2 * (lambda(t(j)) - lambda(t(j-1)))) ...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(3-2))) * delta_t^(-1));
                E_inv_yij_miss_1{i}{j}(2) = (lambda(t(j)) - lambda(t(j-1)+t_int*(3-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1)+t_int*(3-2)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(3-2))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(3-2))) / (lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1)+t_int*(3-2)))...
                    * ((lambda(t(j-1)+t_int*(3-2)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(3-2)))^2 * (lambda(t(j)) - lambda(t(j-1)))) ...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(3-2))) * delta_t^(-1));
                E_inv_yij_miss_1{i}{j}(1) = (lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1)+t_int*(3-2))) / ...
                    (eta*(lambda(t(j-1)+t_int*(3-2)) - lambda(t(j-1)))^2 * (lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1))))+...
                    (lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(3-2)) - lambda(t(j-1)))...
                    * ((lambda(t(j)) - lambda(t(j-1)+t_int*(3-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1)))^2 * (lambda(t(j)) - lambda(t(j-1)))) ...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(3-1)) - lambda(t(j-1))) * delta_t^(-1));

                E_yij_obs{i} = [E_yij_obs{i}, E_yij_miss_1{i}{j}(1), E_yij_miss_1{i}{j}(2), E_yij_miss_1{i}{j}(3)];
                E_inv_yij_obs{i} = [E_inv_yij_obs{i}, E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3)];
                negative_num = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3)];
                if any(negative_num < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end


            elseif abs(t(j) - t(j-1) - t_int*4) < epsilon
                delta_t = y(j) - y(j-1);

                E_yij_miss_1{i}{j}(4) = delta_t * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-1)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))) / (lambda(t(j)) - lambda(t(j-1)));
                E_yij_miss_1{i}{j}(3) = delta_t * (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-2))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))) / (lambda(t(j)) - lambda(t(j-1)));
                E_yij_miss_1{i}{j}(2) = delta_t * (lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1)+t_int*(4-3))) / (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-3)))...
                    * (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))) ...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))) / (lambda(t(j)) - lambda(t(j-1)));
                E_yij_miss_1{i}{j}(1) = delta_t * (lambda(t(j-1)+t_int*(4-3)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1)))...
                    * (lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)))...
                    * (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)));

                E_inv_yij_miss_1{i}{j}(4) = (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-2))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(4-1)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-1)))...
                    * ((lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1)+t_int*(4-3))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(4-2)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2)))...
                    * ((lambda(t(j-1)+t_int*(4-3)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(4-3)))^2 * (lambda(t(j)) - lambda(t(j-1))))...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))) * delta_t^(-1)));
                E_inv_yij_miss_1{i}{j}(3) = (lambda(t(j)) - lambda(t(j-1)+t_int*(4-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-2)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2))) / (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-2)))...
                    * ((lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(4-2)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-2)))...
                    * ((lambda(t(j-1)+t_int*(4-3)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(4-3)))^2 * (lambda(t(j)) - lambda(t(j-1))))...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))) * delta_t^(-1)));
                E_inv_yij_miss_1{i}{j}(2) = (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-2))) / ...
                    (eta*(lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1)+t_int*(4-3)))^2 * (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-3))))...
                    + (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-3))) / (lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1)+t_int*(4-3)))...
                    * ((lambda(t(j)) - lambda(t(j-1)+t_int*(4-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-3)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(4-1)))) ...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(4-1))) / (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-3))) ...
                    * ((lambda(t(j-1)+t_int*(4-3)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(4-3)))^2 * (lambda(t(j)) - lambda(t(j-1)))) ...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-3))) * delta_t^(-1)));
                E_inv_yij_miss_1{i}{j}(4) = (lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1)+t_int*(4-3))) / ...
                    (eta*(lambda(t(j-1)+t_int*(4-3)) - lambda(t(j-1)))^2 * (lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1))))...
                    + (lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1)+t_int*(4-3)))...
                    * ((lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-2))) / ...
                    (eta*(lambda(t(j-1)+t_int*(4-2)) - lambda(t(j-1)))^2 * (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1))))...
                    + (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)+t_int*(4-2)))...
                    * ((lambda(t(j)) - lambda(t(j-1)+t_int*(4-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(4-1)) - lambda(t(j-1)))^2 * (lambda(t(j)) - lambda(t(j-1))))...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(4-1))) * delta_t^(-1)));

                E_yij_obs{i} = [E_yij_obs{i}, E_yij_miss_1{i}{j}(1), E_yij_miss_1{i}{j}(2), E_yij_miss_1{i}{j}(3), E_yij_miss_1{i}{j}(4)];
                E_inv_yij_obs{i} = [E_inv_yij_obs{i}, E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3), E_inv_yij_miss_1{i}{j}(4)];
                negative_num = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3), E_inv_yij_miss_1{i}{j}(4)];
                if any(negative_num < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end

            elseif abs(t(j) - t(j-1) - t_int*5) < epsilon
                delta_t = y(j) - y(j-1);

                E_yij_miss_1{i}{j}(5) = delta_t * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j)) - lambda(t(j-1)));
                E_yij_miss_1{i}{j}(4) = delta_t * (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j)) - lambda(t(j-1)));
                E_yij_miss_1{i}{j}(3) = delta_t * (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-3))) / (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-3)))...
                    * (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j)) - lambda(t(j-1)));
                E_yij_miss_1{i}{j}(2) = delta_t * (lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-4)))...
                    * (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-4)))...
                    * (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4)))...
                    * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j)) - lambda(t(j-1)));
                E_yij_miss_1{i}{j}(1) = delta_t * (lambda(t(j-1)+t_int*(5-4)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1)))...
                    * (lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)))...
                    * (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)))...
                    * (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)));

                E_inv_yij_miss_1{i}{j}(5) = (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-1)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-1)))...
                    * ((lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-3))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-2)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2)))...
                    * ((t(j-1)+lambda(t_int*(5-3)) - lambda(t(j-1)+t_int*(5-4))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-3)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3)))...
                    * ((lambda(t(j-1)+t_int*(5-4)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-4)))^2 * (lambda(t(j)) - lambda(t(j-1))))...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) * delta_t^(-1))));
                E_inv_yij_miss_1{i}{j}(4) = (lambda(t(j)) - lambda(t(j-1)+t_int*(5-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2))) / (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2)))...
                    * ((lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-3))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-2)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-2)))...
                    * ((lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1)+t_int*(5-4))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-3)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3)))...
                    * ((lambda(t(j-1)+t_int*(5-4)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-4)))^2 * (lambda(t(j)) - lambda(t(j-1))))...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) * delta_t^(-1))));
                E_inv_yij_miss_1{i}{j}(3) = (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-3)))^2 * (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-3))))...
                    + (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-3))) / (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2)))...
                    * ((lambda(t(j)) - lambda(t(j-1)+t_int*(5-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-3)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-1)))...
                    * ((lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1)+t_int*(5-4))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-3)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))))...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-3)))...
                    * ((lambda(t(j-1)+t_int*(5-4)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-4)))^2 * (lambda(t(j)) - lambda(t(j-1))))...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) * delta_t^(-1))));
                E_inv_yij_miss_1{i}{j}(2) = (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-3))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1)+t_int*(5-4)))^2 * (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-1))))...
                    + (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-3)))...
                    * ((lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-4)))^2 * (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-4)))) ...
                    + (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2))) ...
                    * ((lambda(t(j)) - lambda(t(j-1)+t_int*(5-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-4)))^2 * (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4)))) ...
                    + (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-1)))...
                    * ((lambda(t(j-1)+t_int*(5-4)) - lambda(t(j-1))) / ...
                    (eta*(lambda(t(j)) - lambda(t(j-1)+t_int*(5-4)))^2 * (lambda(t(j)) - lambda(t(j-1))))...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-4))) * delta_t^(-1))));
                E_inv_yij_miss_1{i}{j}(1) = (lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1)+t_int*(5-4))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-4)) - lambda(t(j-1)))^2 * (lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1))))...
                    + (lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1)+t_int*(5-4)))...
                    * ((lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-3))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-3)) - lambda(t(j-1)))^2 * (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1))))...
                    + (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)+t_int*(5-3)))...
                    * ((lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-2)) - lambda(t(j-1)))^2 * (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1))))...
                    + (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1))) / (lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)+t_int*(5-2)))...
                    * ((lambda(t(j)) - lambda(t(j-1)+t_int*(5-1))) / ...
                    (eta*(lambda(t(j-1)+t_int*(5-1)) - lambda(t(j-1)))^2 * (lambda(t(j)) - lambda(t(j-1))))...
                    + (lambda(t(j)) - lambda(t(j-1))) / (lambda(t(j)) - lambda(t(j-1)+t_int*(5-1))) * delta_t^(-1))));

                E_yij_obs{i} = [E_yij_obs{i}, E_yij_miss_1{i}{j}(1), E_yij_miss_1{i}{j}(2), E_yij_miss_1{i}{j}(3), E_yij_miss_1{i}{j}(4), E_yij_miss_1{i}{j}(5)];
                E_inv_yij_obs{i} = [E_inv_yij_obs{i}, E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3), E_inv_yij_miss_1{i}{j}(4), E_inv_yij_miss_1{i}{j}(5)];
                negative_num = [E_inv_yij_miss_1{i}{j}(1), E_inv_yij_miss_1{i}{j}(2), E_inv_yij_miss_1{i}{j}(3), E_inv_yij_miss_1{i}{j}(4), E_inv_yij_miss_1{i}{j}(5)];
                if any(negative_num < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end

            else


                E_yij_obs{i} = [E_yij_obs{i}, y(j) - y(j-1)];
                E_inv_yij_obs{i} =[E_inv_yij_obs{i}, 1 / E_yij_obs{i}(j)];
                if any(1 / E_yij_obs{i}(j) < 0)
                    warning('第%d条退化路径，第%d时间点有负数',i,j)
                end

            end

        end

    end

    if j == length(y)

        if abs(t(j) - t_int*24) < epsilon

            E_yij_miss_2{i}{j}(1) = lambda(t(j)+t_int) - lambda(t(j));

            E_inv_yij_miss_2{i}{j}(1) = 1/(lambda(t(j)+t_int) - lambda(t(j)))...
                + 1/(eta*(lambda(t(j)+t_int) - lambda(t(j)))^2);

            E_yij_obs{i}= [E_yij_obs{i}, E_yij_miss_2{i}{j}(1)];
            E_inv_yij_obs{i} =[E_inv_yij_obs{i}, E_inv_yij_miss_2{i}{j}(1)];
            negative_num = [E_inv_yij_miss_2{i}{j}(1)];
            if any(negative_num < 0)
                warning('第%d条退化路径，第%d时间点有负数',i,j)
            end

        elseif abs(t(j) - t_int*23) < epsilon

            E_yij_miss_2{i}{j}(1) = lambda(t(j)+t_int) - lambda(t(j));
            E_yij_miss_2{i}{j}(2) = lambda(t(j)+t_int*2) - lambda(t(j)+t_int);

            E_inv_yij_miss_2{i}{j}(1) = 1/(lambda(t(j)+t_int) - lambda(t(j)))...
                + 1/(eta*(lambda(t(j)+t_int) - lambda(t(j)))^2);
            E_inv_yij_miss_2{i}{j}(2) = 1/(lambda(t(j)+t_int*2) - lambda(t(j)+t_int))...
                + 1/(eta*(lambda(t(j)+t_int*2) - lambda(t(j)+t_int))^2);

            E_yij_obs{i}= [E_yij_obs{i}, E_yij_miss_2{i}{j}(1), E_yij_miss_2{i}{j}(2)];
            E_inv_yij_obs{i} =[E_inv_yij_obs{i}, E_inv_yij_miss_2{i}{j}(1), E_inv_yij_miss_2{i}{j}(2)];
            negative_num = [E_inv_yij_miss_2{i}{j}(1), E_inv_yij_miss_2{i}{j}(2)];
            if any(negative_num < 0)
                warning('第%d条退化路径，第%d时间点有负数',i,j)
            end

        elseif abs(t(j) - t_int*22) < epsilon

            E_yij_miss_2{i}{j}(1) = lambda(t(j)+t_int) - lambda(t(j));
            E_yij_miss_2{i}{j}(2) = lambda(t(j)+t_int*2) - lambda(t(j)+t_int);
            E_yij_miss_2{i}{j}(3) = lambda(t(j)+t_int*3) - lambda(t(j)+t_int*2);

            E_inv_yij_miss_2{i}{j}(1) = 1/(lambda(t(j)+t_int) - lambda(t(j)))...
                + 1/(eta*(lambda(t(j)+t_int) - lambda(t(j)))^2);
            E_inv_yij_miss_2{i}{j}(2) = 1/(lambda(t(j)+t_int*2) - lambda(t(j)+t_int))...
                + 1/(eta*(lambda(t(j)+t_int*2) - lambda(t(j)+t_int))^2);
            E_inv_yij_miss_2{i}{j}(3) = 1/(lambda(t(j)+t_int*3) - lambda(t(j)+t_int*2))...
                + 1/(eta*(lambda(t(j)+t_int*3) - lambda(t(j)+t_int*2))^2);

            E_yij_obs{i}= [E_yij_obs{i}, E_yij_miss_2{i}{j}(1), E_yij_miss_2{i}{j}(2), E_yij_miss_2{i}{j}(3)];
            E_inv_yij_obs{i} =[E_inv_yij_obs{i}, E_inv_yij_miss_2{i}{j}(1), E_inv_yij_miss_2{i}{j}(2), E_inv_yij_miss_2{i}{j}(3)];
            negative_num = [E_inv_yij_miss_2{i}{j}(1), E_inv_yij_miss_2{i}{j}(2), E_inv_yij_miss_2{i}{j}(3)];
            if any(negative_num < 0)
                warning('第%d条退化路径，第%d时间点有负数',i,j)
            end

        elseif abs(t(j) - t_int*21) < epsilon

            E_yij_miss_2{i}{j}(1) = lambda(t(j)+t_int) - lambda(t(j));
            E_yij_miss_2{i}{j}(2) = lambda(t(j)+t_int*2) - lambda(t(j)+t_int);
            E_yij_miss_2{i}{j}(3) = lambda(t(j)+t_int*3) - lambda(t(j)+t_int*2);
            E_yij_miss_2{i}{j}(4) = lambda(t(j)+t_int*4) - lambda(t(j)+t_int*3);

            E_inv_yij_miss_2{i}{j}(1) = 1/(lambda(t(j)+t_int) - lambda(t(j)))...
                + 1/(eta*(lambda(t(j)+t_int) - lambda(t(j)))^2);
            E_inv_yij_miss_2{i}{j}(2) = 1/(lambda(t(j)+t_int*2) - lambda(t(j)+t_int))...
                + 1/(eta*(lambda(t(j)+t_int*2) - lambda(t(j)+t_int))^2);
            E_inv_yij_miss_2{i}{j}(3) = 1/(lambda(t(j)+t_int*3) - lambda(t(j)+t_int*2))...
                + 1/(eta*(lambda(t(j)+t_int*3) - lambda(t(j)+t_int*2))^2);
            E_inv_yij_miss_2{i}{j}(4) = 1/(lambda(t(j)+t_int*4) - lambda(t(j)+t_int*3))...
                + 1/(eta*(lambda(t(j)+t_int*4) - lambda(t(j)+t_int*3))^2);

            E_yij_obs{i}= [E_yij_obs{i}, E_yij_miss_2{i}{j}(1), E_yij_miss_2{i}{j}(2), E_yij_miss_2{i}{j}(3), E_yij_miss_2{i}{j}(4)];
            E_inv_yij_obs{i} =[E_inv_yij_obs{i}, E_inv_yij_miss_2{i}{j}(1), E_inv_yij_miss_2{i}{j}(2), E_inv_yij_miss_2{i}{j}(3), E_inv_yij_miss_2{i}{j}(4)];

            negative_num = [E_inv_yij_miss_2{i}{j}(1), E_inv_yij_miss_2{i}{j}(2), E_inv_yij_miss_2{i}{j}(3), E_inv_yij_miss_2{i}{j}(4)];
            if any(negative_num < 0)
                warning('第%d条退化路径，第%d时间点有负数',i,j)
            end
        end

    end

    E_yij{i} = E_yij_obs{i};

    E_inv_yij{i} = E_inv_yij_obs{i};
end


end
